#ifndef CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_08_ZERO_MATRIX_ZEROMATRIX_HPP_
#define CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_08_ZERO_MATRIX_ZEROMATRIX_HPP_

#include <vector>

void zeroMatrix(std::vector<std::vector<int>>& matrix);

#endif  // CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_08_ZERO_MATRIX_ZEROMATRIX_HPP_
