#ifndef CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_01_REMOVE_DUPS_REMOVEDUPS_HPP_
#define CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_01_REMOVE_DUPS_REMOVEDUPS_HPP_

#include "LinkedListUnique.hpp"

namespace LL = LinkedListUnique;

void removeDups(p_node_t& head);

#endif  // CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_01_REMOVE_DUPS_REMOVEDUPS_HPP_
