#ifndef CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_05_SUM_LISTS_SUMLISTSFORWARD_HPP_
#define CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_05_SUM_LISTS_SUMLISTSFORWARD_HPP_

#include "LinkedListUnique.hpp"

namespace LL = LinkedListUnique;

p_node_t sumListsForward(p_node_t& l1, p_node_t& l2);

#endif  // CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_05_SUM_LISTS_SUMLISTSFORWARD_HPP_
