#ifndef CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_01_IS_UNIQUE_ISUNIQUE_HPP_
#define CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_01_IS_UNIQUE_ISUNIQUE_HPP_

#include <string>

bool isUnique(const std::string& s);

#endif  // CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_01_IS_UNIQUE_ISUNIQUE_HPP_
