#ifndef CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_08_LOOP_DETECTION_DETECTLOOP_HPP_
#define CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_08_LOOP_DETECTION_DETECTLOOP_HPP_

#include "LinkedListShared.hpp"

namespace LL = LinkedListShared;

p_node_t detectLoop(const p_node_t& head);

#endif  // CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_08_LOOP_DETECTION_DETECTLOOP_HPP_
