#ifndef CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_06_PALINDROME_PALINDROME_HPP_
#define CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_06_PALINDROME_PALINDROME_HPP_

#include "LinkedListUnique.hpp"

namespace LL = LinkedListUnique;

bool palindrome(const p_node_t& head);

#endif  // CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_06_PALINDROME_PALINDROME_HPP_
