#ifndef CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_05_ONE_WAY_ONEWAY_HPP_
#define CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_05_ONE_WAY_ONEWAY_HPP_

#include <string>

bool oneWay(const std::string& s1, const std::string& s2);

#endif  // CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_05_ONE_WAY_ONEWAY_HPP_
