#ifndef CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_04_PARTITION_PARTITION_HPP_
#define CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_04_PARTITION_PARTITION_HPP_

#include "LinkedListUnique.hpp"

namespace LL = LinkedListUnique;

void partition(p_node_t& head, int x);

#endif  // CTCI_6TH_EDITION_CPP_02_LINKED_LISTS_04_PARTITION_PARTITION_HPP_
