#ifndef CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_09_STRING_ROTATION_STRINGROTATION_HPP_
#define CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_09_STRING_ROTATION_STRINGROTATION_HPP_

#include <string>

bool stringRotation(const std::string& origin, const std::string& rotation);

#endif  // CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_09_STRING_ROTATION_STRINGROTATION_HPP_
