#ifndef CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_03_URLIFY_URLIFY_HPP_
#define CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_03_URLIFY_URLIFY_HPP_

#include <string>

int urlify(std::string& s, int n);

#endif  // CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_03_URLIFY_URLIFY_HPP_
