#ifndef CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_07_ROTATE_MATRIX_ROTATEMATRIX_HPP_
#define CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_07_ROTATE_MATRIX_ROTATEMATRIX_HPP_

#include <vector>

void rotateMatrix(std::vector<std::vector<int>>& m);

#endif  // CTCI_6TH_EDITION_CPP_01_ARRAYS_AND_STRINGS_07_ROTATE_MATRIX_ROTATEMATRIX_HPP_
