#ifndef CTCI_6TH_EDITION_CPP_03_STACKS_AND_QUEUES_05_SORT_STACK_SORTSTACK_HPP_
#define CTCI_6TH_EDITION_CPP_03_STACKS_AND_QUEUES_05_SORT_STACK_SORTSTACK_HPP_

#include <stack>

using Stack = std::stack<int>;

void sortStack(Stack& s);

#endif  // CTCI_6TH_EDITION_CPP_03_STACKS_AND_QUEUES_05_SORT_STACK_SORTSTACK_HPP_
